[package]
name = "sov-encryption"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
publish.workspace = true

[features]
default = ["aes-encryption"]
aes-encryption = ["aes-gcm", "rand"]
unix-client = []

[dependencies]
aes-gcm = { version = "0.10", default-features = false, features = ["aes", "alloc", "getrandom"], optional = true }
rand = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
hex = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
schemars = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
secrecy = { version = "0.10", features = ["serde"] }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
